workbenchdev/Workbench

src/Library/demos/Application window/main.blp
src/Previewer/DBusPreviewer.js
src/Previewer/External.js
src/Previewer/Internal.js
src/Previewer/Previewer.js
src/Previewer/vala-previewer/previewer.vala
src/window.blp

Fixes https://github.com/sonnyp/Workbench/issues/60
Needs the Vala equivalent and ready to go (as far as I can tell)

Support root property updates for JS

---

src/Previewer/Internal.js

Fixes https://github.com/sonnyp/Workbench/issues/130
Alex confirmed there's probably no way to mark those as non writeable in a way that bindings would understand.

Fix a crash when updating AdwWindow objects

---

Makefile
src/Previewer/Previewer.js
src/Previewer/utils.js
src/workbench.gresource.xml
test/workbench.test.js

This implementation is more in line with what GtkBuilder actually does which is looking at each object and asserting that the parent object implements GtkBuildable.
Fixes https://github.com/sonnyp/Workbench/issues/135
Could not use GLib.MarkupParser because of https://gitlab.gnome.org/GNOME/gjs/-/issues/448#note_1499305

Prevent false positive in assertBuildable

---

re.sonny.Workbench.json
src/PanelUI.js
src/util.js

Closes https://github.com/sonnyp/Workbench/issues/148
The current implementation (in `main`) is fairly naive; on each text update, Workbench sends the whole text to the Blueprint LSP, waits for an event and then update the Builder.
The whole thing is asynchronous, and it takes longer to complete than the time it takes to get the next "update" signal.
This PR fixes that by waiting for the latest compile before starting the next one.
Here are a couple of ideas on how to make Blueprint updates even faster but we I'll need to measure impact first
1. Extract the event to be its own routine (outside of  `compileBlueprint`) 
2. Implement LSP text range updates
3. Embed/use pyjobject 
4. Use https://github.com/Prince781/lsp-glib

Throttle Blueprint updates

---

src/Previewer/External.js
src/Previewer/Previewer.js
src/Previewer/vala-previewer/previewer.vala

If there was no original id - Vala preview would fail with
> No UI definition loaded yet.
because of
> Error: Expected type string for argument 'string' but got type
undefined

Fix Vala external preview

---

.vscode/settings.json
Makefile
re.sonny.Workbench.Devel.json
re.sonny.Workbench.json
src/workbench

sdk extensions are not installed automatically - even when using sdk as runtime.
Inspired by https://github.com/flathub/org.freedesktop.Sdk.Extension.vala/blob/9e747d847c03ede6a7f686d0a45ac1ef896f3355/org.freedesktop.Sdk.Extension.vala.yml
For some reason vala-language-server had to be updated to a newer revision.

Bundle vala-language-server

---

CONTRIBUTING.md
build-aux/list-demo-blp-files.sh
src/Library/Library.js
src/app.gresource.xml
src/meson.build

With this change, it's only needed to add the files to `src/Library/demos`.
Fiddling with gresource, meson, ... is error prone and not very begineer friendly.
We are now loading the demo files from disk instead of from a gresource. It will be fine for now but we can optimize later when we have many entries.

Simplify Library contrbutions

---

src/Library/demos/Button/main.blp
src/Library/demos/Button/main.css
src/Library/demos/Button/main.js
src/Library/demos/Button/main.json

Created Button Demo under User Interface Section in Library
Issue #69

library: Add Button entry

---

src/Library/Library.blp
src/Library/Library.js
src/Previewer/Internal.js

Depends on https://github.com/sonnyp/Workbench/pull/203
Allows for split view and navigating entries easily
Let's wait for GNOME 44 which should solve the "Library is ready" notification issue.
* https://matrix.to/#/!zdrdMLdnhhVKlafMSp:gnome.org/$6MHGhtO1QdCjUMd07abOJVWgya3PrjYxvm1sGcfYzok
* https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5555

library: Make window non modal

---

src/Library/demos/Text Colors/main.blp
src/Library/demos/Text Colors/main.js
src/Library/demos/Text Colors/main.json
src/about.js

This demo showcases how you can use Pango attributes to easily apply complex formatting to labels.

library: Add Text Colors demo

---

src/Library/demos/Scale/main.blp
src/Library/demos/Scale/main.js
src/Library/demos/Scale/main.json

Added Scale Entry under User Interface Section in Library
Issue #69

library: Add Scale entry

---

data/app.gschema.xml
src/Library/demos/Welcome/main.blp
src/Previewer/Previewer.js
src/Previewer/crasher.vala
src/Previewer/utils.js
src/actions.js
src/window.blp
src/window.js

Fixes https://github.com/sonnyp/Workbench/issues/215
Partially relates to https://github.com/sonnyp/Workbench/issues/218
We have a process that check if the preview is going to crash but
1. It does not prevent every possible crash
2. It makes editing slower
3. It does not provide good feedback to users
4. At least on Fedora it triggers an abrt report on every crash
This PR adds a few safeguards to return before hitting known crashes.
In addition, the process has been disabled by default under "Safe Mode" to make updates faster.
A "Auto-Update" setting was enabled as well for the preview and is enabled by default.
I don't know yet if "Safe Mode" and "Auto-Update" modes will remain.

Improve crash prevention

---

src/Library/demos/Calendar/main.blp
src/Library/demos/Calendar/main.js
src/Library/demos/Calendar/main.json

Added Calendar Demo under User Interface Section in Library
Issue #69

library: Add Calendar Entry

---

src/Library/demos/Color Dialog/main.blp
src/Library/demos/Color Dialog/main.js
src/Library/demos/Color Dialog/main.json

Adds Color Dialog entry.
Issue #69

library: Add Color Dialog entry

---

src/Library/demos/Toggle Button/main.blp
src/Library/demos/Toggle Button/main.js
src/Library/demos/Toggle Button/main.json

Added Toggle Button Entry/Demo under User Interface section in Library.
Issue #69

library: Add Toggle Button Entry 

---

.gitmodules

The `.gitmodules` file was pointing at https://gitlab.gnome.org/sonny/blueprint-compiler/, which doesn't contain the referenced commit.
Fixes #246

Switch to jwestman/blueprint-compiler repo

---

src/Library/demos/Text Fields/main.blp
src/about.js
src/window.blp

Following what the GNOME HIG recommends I made some changes:
- Remove keyboard shortcut from tooltips, it's currently not recommended to put them there
- Make all tooltips use header capitalization
- Add a tooltip to the main menu

Improve tooltips

---

src/Library/demos/Header Bar/main.blp
src/Library/demos/Header Bar/main.json

Adds Header Bar entry.
Issue #69

library: Add Header Bar entry

---

src/Library/demos/Web View/main.blp
src/Library/demos/Web View/main.js
src/Library/demos/Web View/main.json

Add WebView Entry
Closes #276 
Also I would like to know, where should I include the status page for this demo - title, description, links etc. Since the webview takes up the entire window. I was thinking initially when the demo loads, we show the status page in the window and when a link is entered, the webview is shown. Wdyt?

library: Add WebView entry

---

src/Library/Library.blp
src/Library/demos/Tab View/main.blp
src/Library/demos/Tab View/main.js
src/Library/demos/Tab View/main.json
src/Library/demos/View Switcher/main.json

Closes #291 
Adds demo entry for ``AdwTabView``. Also creates a new section "Navigation" in the library.

library: Add TabView entry

---

src/Library/demos/Drawing Area/main.blp
src/Library/demos/Drawing Area/main.js
src/Library/demos/Drawing Area/main.json

Fixes https://github.com/sonnyp/Workbench/issues/296
not default color:) to be honest i tried, but i do not know how to get color of gtk context for inverting it, triangle form because it is default form for drawing tasks

Library: Add Drawing area

---

src/Library/demos/About Window/main.blp
src/Library/demos/About Window/main.js
src/Library/demos/About Window/main.json

library: Adds Adw.AboutWindow entry

---

src/Library/demos/Banner/main.blp
src/Library/demos/Banner/main.js
src/Library/demos/Banner/main.json

library: Add AdwBanner entry

---

src/Library/demos/Carousel/main.blp
src/Library/demos/Carousel/main.js
src/Library/demos/Carousel/main.json
src/Library/demos/Carousel/main.vala

library: add Carousel entry

---

src/Library/demos/Avatar/main.js
src/Library/demos/Box/main.blp
src/Library/demos/Box/main.js
src/Library/demos/Color Dialog/main.js
src/Library/demos/Color Dialog/main.json
src/Library/demos/Custom Widget/main.js
src/Library/demos/Dialogs/main.js
src/Library/demos/Dialogs/main.vala
src/Library/demos/Font Dialog/main.js
src/Library/demos/Grid/main.blp
src/Library/demos/HTTP Image/main.js
src/Library/demos/Text Colors/main.js
src/Library/demos/Text View/main.js
src/Library/demos/Web View/main.js
src/Library/demos/WebSocket Client/main.js
src/Library/demos/Welcome/main.js
src/Library/demos/Welcome/main.vala
src/about.js
src/init.js

Signal handlers have semantic around return values.
Let's not encourage developers to use async signal handlers, as it can lead to hard to debug issues.
Also, some other improvements

library: Do not use async handlers

---

src/Library/demos/Progress Bar/main.js

Closes #322
I haven't made any changes to the UI, and I didn't add another progress bar that makes use of setInterval because to pulse the progress bar I'm making use of a setInterval anyway.

library: Update Progress Bar demo

---

src/about.js
src/libworkbench/meson.build
src/libworkbench/workbench-completion-provider.c
src/libworkbench/workbench-completion-provider.h
src/libworkbench/workbench-completion-request.c
src/libworkbench/workbench-completion-request.h
src/libworkbench/workbench.h
src/meson.build

Functionality that is static and performance sensitive can be moved here as necessary, but more importantly it can be used to work around problems with introspection in GJS.
cc #257

feat: add an internal GI library for Workbench

---

src/Library/demos/Location/main.blp
src/Library/demos/Location/main.js
src/Library/demos/Location/main.json

Closes #350 
Implemented the following changes:
- Made the UI interactive by using Revealer
- Used Gtk.SpinButton and Gtk.Dropdown for changing values 
- Covered all 8 properties 
``` Looking for an early review ```

library: Add location entry

---

po/POTFILES
re.sonny.Workbench.Devel.json
re.sonny.Workbench.json
src/PanelStyle.js
src/Previewer/Internal.js
src/about.js
src/langs/css/css.js
src/window.js

Fixes #370
Integrates this language server for GTK CSS flavor: https://github.com/JCWasmx86/GTKCssLanguageServer
Currently the diagnostics are complete, hovering are stubs (As I currently don't have the time to copy-paste the description from MDN), auto-completion is barebones.
This code provided here is enough for showing diagnostics.

Use diagnostics from gtkcsslanguageserver

---

src/Library/demos/Check Button/main.blp
src/Library/demos/Check Button/main.js
src/Library/demos/Check Button/main.json

Closes #336
Right now the inconsistent checkbox is not functioning properly, after it has completed one cycle of inconsistent -> on -> off -> inconsistent, the next time the check button turns on "Mark as Done: On" is logged twice because of ``checkbutton3.active = true`` under case 0, the button triggers ``::toggled`` again.
A review would be appreciated.

library: Add Check Button demo

---

src/langs/vala/workbench-api.vala

As far as I can tell, it is unused
@lw64

Remove application in workbench-api.vala

---

.editorconfig
src/Library/Library.js
src/Library/demos/Audio/main.js
src/Library/demos/Event Controllers/main.js
src/Library/demos/Frame/main.js
src/Library/demos/Overlay/main.js
src/Library/demos/Overlay/main.vala
src/Library/demos/Revealer/main.js
src/Library/demos/Separator/main.js
src/Library/demos/Video/main.js
src/Library/demos/Wallpaper/main.js
src/Previewer/Internal.js
src/Previewer/Previewer.js
src/Previewer/previewer.vala
src/Previewer/previewer.xml
src/langs/vala/Compiler.js
src/langs/vala/workbench-api.vala
src/window.js

Fixes https://github.com/sonnyp/Workbench/issues/428 by adding a new `workbench.resolve('./image.png')` API which returns an absolute file URI.
---
Another way to solve it is that when running a session we can set `pwd` to the session folder and make use of `File.new_for_path('./image.png')` in examples.
One issue is that it can't be used with the "inline" JS preview/runner unless
- each Workbench window becomes a separate process
- or
- we disable inline runner for JS and run in a separate process like Vala
We have a similar problem with the console, it prints stdout/stderr of the Workbench process which is shared between windows. 
I'm not sure yet if this is the right way to go. Since we already have a couple of `workbench.x` APIs, I don't think adding a new one is a huge deal. It might …

library: Use relative paths

---

src/Previewer/previewer.vala
src/Previewer/previewer.xml
src/langs/vala/Compiler.js
src/langs/vala/workbench.vala

Simplify code and allow running Vala code without UI definitions.

Improve Vala previewer

---

src/Library/demos/Navigation Split View/main.blp
src/Library/demos/Navigation Split View/main.json

library: Add Navigation Split View entry

---

src/Library/demos/Scrolled Window/main.blp
src/Library/demos/Scrolled Window/main.js
src/Library/demos/Scrolled Window/main.json

Closes #419
There is an edge case where if the Start/End buttons are pressed when it's already at the edge, the buttons get disabled for the animation duration. Is that problematic and if so, what might be the simplest way to handle it?

library: Add Scrolled Window entry

---

src/Library/demos/Network Monitor/main.blp
src/Library/demos/Network Monitor/main.css
src/Library/demos/Network Monitor/main.js
src/Library/demos/Network Monitor/main.json

Closes #454 
This was a tricky one :)

library: Add Network Monitor demo

---

src/Library/demos/Breakpoints/main.blp
src/Library/demos/Breakpoints/main.js
src/Library/demos/Breakpoints/main.json

closes #407 and closes https://github.com/sonnyp/Workbench/issues/269

library: add Breakpoint entry

---

src/Library/demos/Boxed Lists/main.blp

Super simple addition, with the release of the new 1.4 row widgets, we are not showing new users how to use ```activatable-widget``` property which is useful for deriving your own custom row widget and etc.

Boxed Lists: show off activatable widget property.

---

README.md
data/app.metainfo.xml

There will be more by then but I had a moment to kill so I did this

Update release notes

---

src/Library/demos/Memory Monitor/main.blp
src/Library/demos/Memory Monitor/main.js
src/Library/demos/Memory Monitor/main.json

library: Add Memory Monitor entry

---

src/Library/demos/Tab View/code.rs

Tried porting `TabView` library in rust.
Currently has an error related to `mut` in closure function. Can't seem to fix on my own.
<details>
<summary>Error log</summary>
```
error[E0596]: cannot borrow `tab_count` as mutable, as it is a captured variable in a `Fn` closure
--> code.rs:12:29
|
12 |         add_page(&tab_view, &mut tab_count);
|                             ^^^^^^^^^^^^^^ cannot borrow as mutable
error[E0596]: cannot borrow `tab_count` as mutable, as it is a captured variable in a `Fn` closure
--> code.rs:14:62
|
14 |     overview.connect_create_tab(move |_| add_page(&tab_view, &mut tab_count));
|                                                              ^^^^^^^^^^^^^^ cannot borrow as mutable
warning: variable does not need to be mutable
--> code.rs:9:9
|
9 |     let mut …
```

library: Ported `TabView` in rust

---

src/Library/demos/Navigation View/code.rs

Adds rust version of the `NavigationView` library.
Noticeable differences:
- `switch` of `JavaScript` is replaced with `if-else` statements.
- `current_page` variable is used at two places to avoid multiple function calls.
Lemme know if the `current_page` is unnecessary for the  use case.

library: Ported `NavigationView` to rust

---

src/Library/demos/Grid/code.rs
src/langs/rust/template/Cargo.lock
src/langs/rust/template/Cargo.toml

Also, added dependency for rand.

Add rust demo grid

---

src/Library/demos/Popovers/code.rs

Tried to port Popover, however I am facing a problem as I have been unable to find a function to fetch the name of the popover. It says the .name() function exists, however I can't get it to work. Need some assistance.
Thanks a lot.

library: Ported Popover in RUST

---

src/Library/demos/View Switcher/code.rs
src/Library/demos/View Switcher/main.js
src/Library/demos/View Switcher/main.vala

Check button is not working right now. @Hofer-Julian Plz have a look.

library: Ported View switcher to rust

---

Makefile

`flatpak-builder-lint` requires a positional argument nowadays

Fix `make ci`

---

data/app.metainfo.xml
src/Manuals/DocumentationViewer.blp
src/Manuals/DocumentationViewer.js

* Select the text on search focus (ctrl+k) so the user can type something new to replace the previous search directly
* Fix libadwaita warnings about navigation page not having titles
* Fix an issue where you can't load (because of autoselect) the first filter result
* Reset Manuals when the window has been hidden and reopened (hide-on-close)
* Focus the search
* Reset search

manuals: Fix a couple of bugs

---

src/Library/demos/Actions/main.blp
src/Library/demos/Actions/main.py
src/about.js

This PR ports the Actions demo to Python
I have tried to stay as close as possible to the JS code. Not sure if I should have avoided using lambdas as in the Welcome demo, see [comment](https://github.com/sonnyp/Workbench/pull/570/files#r1372677674). I used lambdas because here it's only for a single statement, whereas in the Welcome demo there were two statements.
The `open_uri` actions somehow don't work yet. Is this something that needs to be fixed on the "core" side or is there something wrong with my code?

library: Port Actions demo to Python

---

src/Library/demos/Breakpoints/main.py
src/Library/demos/Emoji Chooser/main.py
src/Library/demos/Image/main.py
src/Library/demos/Link Button/main.py
src/Library/demos/Menu Button/main.py
src/Library/demos/Overlay/main.py
src/Library/demos/Popovers/main.py
src/Library/demos/Radio Buttons/main.py
src/Library/demos/Separator/main.py
src/Library/demos/Styling with CSS/main.py

I ported a few demos to Python, but keep in mind that I know very little Python and even less Gtk :)

More Python demos

---

src/Library/demos/Memory Monitor/main.vala

Ports Memory Monitor demo to Vala

library: Port Memory Monitor demo to Vala

---

src/langs/python/python-previewer.py

This fixes #745.
Forgot a pretty critical "return" when I ported the Vala previewer, which ran the code which was only supposed to run if a window was already opened. This then immediately destroyed the just created and shown window, leaving just a ghost window open :ghost:. Kinda impressed Gtk still handled everything fine seemingly, except closing the window again. 
What is a bit strange though is that it doesn't even log a warning until you try to close the window.
Also updated the docstring of the Previewer, the old docstring wasn't accurate anymore.

python: fix Previewer not being closable

---

src/Library/demos/Color Picker/main.py

Doesn't work yet. Somehow `Gdk.RGBA` doesn't properly set the color values, only to `(0,0,0,0)`

Library: Port 'Color Picker' to Python

---

src/Library/demos/HTTP Image/code.rs

Related to #796
Replaces the uses of `Gdk.Pixbuf`-related APIs in favour of `Gdk.Texture`, as Pixbufs have been de-emphasized in GTK4.

library: Remove Gdk.Pixbuf-related APIs in HTTP Image Rust demo

---

data/app.metainfo.xml
data/meson.build

- Add the `<developer><name>` tag
- Mark the `<developer_name>` tag as deprecated
- Remove the second appstreamcli validation
- Improve appstreamcli arguments

appdata: Improve appdata for AppStream 1.0
