src/Previewer/External.js
src/lsp/LSPClient.js

In case of crash. 
I can't really find a way to make it crash anymore so I added a snippet of code to trigger it after 5 seconds

Restart the Blueprint language server on exit

---

data/re.sonny.Workbench.metainfo.xml
docs/design-goals.md
src/Previewer/External.js
src/Previewer/Previewer.js
src/window.js

Related https://github.com/sonnyp/Workbench/issues/93

Add support for previewing with signals

---

data/re.sonny.Workbench.metainfo.xml
src/Previewer/External.js
src/Previewer/vala-previewer/previewer.vala

Prevent dbusproxy from taking down Workbench

---

src/Previewer/DBusPreviewer.js
src/Previewer/External.js
src/Previewer/Previewer.js
src/Previewer/vala-previewer/previewer.vala

Closes https://github.com/sonnyp/Workbench/issues/86

External preview: open window with same size as internal preview

---

data/re.sonny.Workbench.gschema.xml
src/Document.js
src/util.js
src/window.blp
src/window.js

Fixes https://github.com/sonnyp/Workbench/issues/84.

Change confirmation dialog to toasts

---

src/Previewer/Previewer.js
src/util.js
src/window.js

Closes https://github.com/sonnyp/Workbench/issues/93

Binding signal handlers by exporting functions

---

src/PanelStyle.js
src/PanelUI.js
src/Previewer/DBusPreviewer.js
src/Previewer/External.js
src/Previewer/Internal.js
src/Previewer/Previewer.js
src/Previewer/vala-previewer/previewer.vala
src/util.js
src/window.js
src/workbench.gresource.xml

Inline CSS errors

---

src/lsp/LSPClient.js

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol

Fix LSP implementation

---

src/Previewer/Internal.js
src/Previewer/Previewer.js
src/Previewer/vala-previewer/meson.build
src/Previewer/vala-previewer/previewer.vala

Fixes https://github.com/sonnyp/Workbench/issues/133

Destroy preview window on close

---

.vscode/extensions.json
re.sonny.Workbench.Devel.json
re.sonny.Workbench.json
src/PanelCode.js
src/Previewer/DBusPreviewer.js
src/Previewer/External.js
src/Previewer/Internal.js
src/Previewer/Previewer.js
src/Previewer/previewer.vala
src/Previewer/previewer.xml
src/langs/vala/Compiler.js
src/langs/vala/workbench-api.vala
src/util.js
src/window.js

Do not require session-bus and make DBus async
Async DBus will prevent blocking the UI. Fixes
https://github.com/sonnyp/Workbench/issues/90
Removing sesson-bus permission will make Workbench fully sandboxed see https://github.com/flathub/flathub/issues/2785

Do not require session-bus

---

src/PanelUI.js
src/Previewer/Previewer.js
src/langs/blueprint/blueprint.js
src/lsp/LSPClient.js

Use a method instead of notification to get XML
Clear the preview when there is no XML
Fixes https://github.com/sonnyp/Workbench/issues/189

Improve Blueprint previewer

---

src/Library/demos/Spinner/main.blp
src/Library/demos/Spinner/main.js
src/Library/demos/Spinner/main.json

Added Spinner Demo under User Interface Section in Library
Issue #69

library: Add Spinner entry

---

src/IconLibrary/main.blp
src/about.js

IconLibrary: Move the search bar to header

---

src/langs/blueprint/blueprint.js
src/lsp/LSPClient.js

Fixes https://github.com/sonnyp/Workbench/issues/240

lsp: Fix reading large incoming json-rpc messages

---

src/Library/demos/View Switcher/main.blp
src/Library/demos/View Switcher/main.js
src/Library/demos/View Switcher/main.json

Simple blueprint demo showing off the ViewSwitcher Pattern

library: Add ViewSwitcher entry

---

src/Library/demos/Preferences Window/main.blp
src/Library/demos/Preferences Window/main.js
src/Library/demos/Preferences Window/main.json

I'm still not sure why I am getting this error.
closes #288

library: add PreferencesWindow entry

---

src/about.js

add Jose as a contributor

---

src/Library/demos/Animation/main.blp
src/Library/demos/Animation/main.css
src/Library/demos/Animation/main.js
src/Library/demos/Animation/main.json

library: Add Animation entry

---

src/Library/demos/Drop Down/main.blp
src/Library/demos/Drop Down/main.js
src/Library/demos/Drop Down/main.json
src/Library/demos/Drop Down/main.vala

Fixes https://github.com/sonnyp/Workbench/issues/268

library: add DropDown entry

---

src/Library/demos/Action Bar/main.blp
src/Library/demos/Action Bar/main.js
src/Library/demos/Action Bar/main.json
src/Library/demos/List Model/main.blp
src/Library/demos/List Model/main.js
src/Library/demos/List Model/main.json

Kept the entry minimalistic so as to create UI as shown in the documentation:

library: Add Actionbar entry

---

re.sonny.Workbench.Devel.json
re.sonny.Workbench.json
src/DocumentationViewer.blp
src/DocumentationViewer.js

DocumentationViewer: Add missing docs from gtk-doc

---

src/Library/demos/Text Fields/main.vala

Adds Vala code demo for Text Fields

library: Add vala demo for Text Fields

---

src/Library/demos/Color Dialog/main.vala
src/Library/demos/HTTP Image/main.vala

Ports HTTP Image and Color Dialog demos to Vala

library: Port HTTP Image, Color Dialog demos to Vala

---

src/Library/demos/Scale/main.vala

library: Add vala demo for Scale

---

src/Library/demos/Drop Zone/main.blp
src/Library/demos/Drop Zone/main.css
src/Library/demos/Drop Zone/main.js
src/Library/demos/Drop Zone/main.json
src/Library/demos/Drop Zone/main.vala

library: add Drop Zone Entry

---

src/Library/demos/Label/main.blp
src/Library/demos/Label/main.js
src/Library/demos/Label/main.json

library: add Label entry

---

re.sonny.Workbench.Devel.json
re.sonny.Workbench.json
src/about.js

Update to Blueprint 0.10.0

---

src/Library/demos/Scale/main.blp
src/Library/demos/Scale/main.js
src/Library/demos/Scale/main.vala

Library: add Scale Button to Scale Entry

---

src/Library/demos/Preferences Window/main.vala
src/about.js

Adds Vala code demo for Preferences Window

library: Add vala demo for Preferences Window

---

src/Library/demos/List Model/main.vala
src/Library/demos/List View Widgets/main.vala
src/about.js

Ports ListModel and List View Widgets demos to Vala

library: Port ListModel and List View Widgets demos to Vala

---

src/Library/demos/Boxed Lists/main.blp

main.blp: add switch row

---

src/Library/demos/Button/main.vala

Adds Vala code demo for Button

library: Add vala demo for Button

---

src/Library/demos/Drag and Drop/main.json

Closes https://github.com/sonnyp/Workbench/issues/460

Enable autorun for Drag and Drop

---

src/DocumentationViewer.js

Documentation Viewer: Filter irrelevant docs

---

src/Library/demos/Boxed Lists/main.blp

Add spin row to boxed list entry

---

src/Library/demos/Text View/main.vala

Adds Vala code demo for TextView

library: Add vala demo for Text View

---

src/Library/demos/Account/main.vala
src/Library/demos/Color Picker/main.vala
src/Library/demos/Email/main.vala
src/Library/demos/Location/main.vala
src/Library/demos/Screenshot/main.vala
src/Library/demos/Wallpaper/main.vala

Ports the system APIs demos to Vala

library: Port system APIs demos to Vala

---

src/Library/demos/Event Controllers/main.vala

Ports the Event Controllers demo to Vala

library: Port Event Controllers demo to Vala

---

src/Library/demos/Power Profile Monitor/main.blp
src/Library/demos/Power Profile Monitor/main.js
src/Library/demos/Power Profile Monitor/main.json

library: Add Power Profile Monitor demo

---

src/DocumentationViewer.js

Reference: 
* https://gitlab.gnome.org/GNOME/devhelp/-/blob/0d6cfe1f08e365745b357accde43c21b4308f842/devhelp/dh-web-view.c#L71
* https://gitlab.gnome.org/GNOME/devhelp/-/blob/0d6cfe1f08e365745b357accde43c21b4308f842/devhelp/dh-web-view.c#L502

manuals: Hide sidebar using CSS

---

src/Library/demos/Banner/code.rs

Ported `Banner` library to rust.

library: Added `Banner` in rust

---

src/Library/demos/Checkboxes/code.rs

Recently Learned about the availability of Rust in the Workbench.
I have added the checkbox implementation in Rust . It works on fine on the builder on my machine. Please Check it.

Library: ported `Checkbox` in Rust

---

src/Library/demos/Overlay/code.rs

I have added overlay in rust.
Please review

library: ported `Overlay` in rust

---

src/Library/demos/Radio Buttons/code.rs

Checked the JS implementation and tried to port RadioButton in RUST. Please check and let me know as it works on my development environment. Thank you.

library: Ported `RadioButton` in RUST

---

src/Library/demos/Spinner/code.rs
src/about.js

Ported the RUST implementation of Spinner in RUST, please check it out.
Also updated about.js as told on my first PR.

library: Ported `Spinner` in RUST

---

src/Library/demos/Picture/code.rs

library: ported `Picture` in rust

---

src/Library/demos/Menu Button/main.blp
src/window.blp

For Workbench itself as well as for the menu button demo

Add Rust website to bookmarks

---

src/Library/demos/Menu Button/code.rs
src/Library/demos/Menu Button/main.blp

library: Use dedicated row widgets in Menu Button demo

---

src/Library/demos/Accessibility/main.js

Modified inversion of state in function toggleButton for better clarity. Also, corresponds better to suggested Rust example (https://github.com/sonnyp/Workbench/pull/664).

library: Improve JavaScript demo Accessibility

---

src/Library/demos/Web View/code.rs
src/Previewer/meson.build
src/Previewer/previewer.vala
src/langs/rust/template/Cargo.lock
src/langs/rust/template/Cargo.toml

- Ensure types of WebKitGtk 6.0 in previewer.vala
- Add WebView demo

library: Add WebView demo in Rust

---

src/Library/demos/Audio/main.vala
src/Library/demos/Image/main.vala
src/Library/demos/Picture/main.vala
src/Library/demos/Video/main.vala

This PR ports the Audio, Image, Picture and Video demos to Vala.

library: Port Media, Image and Picture demos to Vala

---

src/Library/demos/Box/main.vala
src/Library/demos/Flow Box/main.vala

This PR ports the Flowbox and Box demos to Vala.

library: Port Flowbox and Box demos to Vala

---

src/Library/demos/CSS Gradients/main.py

Marking as draft, since it doesn't work for me - see #713

Library: Port 'CSS Gradients' to Python

---

src/Library/demos/Animation/main.vala

Ports the Animation demo to Vala

library: Port Animation demo to Vala

---

src/Library/demos/Overlay Split View/main.vala

Ports the Overlay Split View demo to Vala

library: Port Overlay Split View demo to Vala

---

src/Library/demos/Text Colors/main.vala

Ports the Text Colors demo to Vala

library: Port Text Colors demo to Vala

---

src/Library/demos/Tab View/main.vala

Ports the Tab View demo to Vala

library: Port Tab View demo to Vala

---

src/Library/demos/Navigation View/main.vala

Ports the Navigation View demo to Vala

library: Port Navigation View demo to Vala

---

src/Library/demos/Open File/main.vala

Ports the Open File demo to Vala

library: Port Open File demo to Vala

---

src/Library/demos/Launcher/main.vala

Ports the Launcher demo to Vala

library: Port Launcher demo to Vala

---

src/Library/demos/Calendar/main.vala

Ports the Calendar demo to Vala

library: Port Calendar demo to Vala

---

src/Library/demos/Column View/main.vala

Ports the Column View demo to Vala

library: Port Column View demo to Vala

---

src/Library/demos/HTTP Request/main.vala

Ports the HTTP Request demo to Vala

library: Port HTTP Request demo to Vala

---

src/Library/demos/Web View/main.vala

Ports the Web View demo to Vala

library: Port Web View demo to Vala

---

src/Library/demos/Search/main.py

Library: Port 'Search' to Python

---

src/Library/demos/Flow Box/main.py

Library: Port 'Flow Box' to Python

---

src/Library/demos/Clamp/main.py

I seem to have forgotten this earlier on.

Library: Port 'Clamp' to Python
